-- База данных на каждый сервис (database-per-service): свой пользователь, своя БД, доступа к чужим БД нет
CREATE USER identity WITH PASSWORD 'identity';
CREATE DATABASE identity_db OWNER identity;
REVOKE ALL ON DATABASE identity_db FROM PUBLIC;
GRANT ALL ON DATABASE identity_db TO identity;
CREATE USER reference WITH PASSWORD 'reference';
CREATE DATABASE reference_db OWNER reference;
REVOKE ALL ON DATABASE reference_db FROM PUBLIC;
GRANT ALL ON DATABASE reference_db TO reference;
CREATE USER vacancy WITH PASSWORD 'vacancy';
CREATE DATABASE vacancy_db OWNER vacancy;
REVOKE ALL ON DATABASE vacancy_db FROM PUBLIC;
GRANT ALL ON DATABASE vacancy_db TO vacancy;
CREATE USER resume WITH PASSWORD 'resume';
CREATE DATABASE resume_db OWNER resume;
REVOKE ALL ON DATABASE resume_db FROM PUBLIC;
GRANT ALL ON DATABASE resume_db TO resume;
CREATE USER application WITH PASSWORD 'application';
CREATE DATABASE application_db OWNER application;
REVOKE ALL ON DATABASE application_db FROM PUBLIC;
GRANT ALL ON DATABASE application_db TO application;
CREATE USER recommendation WITH PASSWORD 'recommendation';
CREATE DATABASE recommendation_db OWNER recommendation;
REVOKE ALL ON DATABASE recommendation_db FROM PUBLIC;
GRANT ALL ON DATABASE recommendation_db TO recommendation;
CREATE USER notification WITH PASSWORD 'notification';
CREATE DATABASE notification_db OWNER notification;
REVOKE ALL ON DATABASE notification_db FROM PUBLIC;
GRANT ALL ON DATABASE notification_db TO notification;
