// Каталог ошибок API (ДЗ 2). Формат: КОД: [HTTP-статус, сообщение для пользователя]
export const ERRORS = {
    BAD_REQUEST: [400, 'Некорректный запрос'] as [number, string],
    INVALID_CODE: [400, 'Неверный или просроченный код подтверждения'] as [number, string],
    INVALID_CURRENT_PASSWORD: [400, 'Текущий пароль указан неверно'] as [number, string],
    UNAUTHORIZED: [401, 'Требуется авторизация'] as [number, string],
    TOKEN_EXPIRED: [401, 'Срок действия токена истёк'] as [number, string],
    INVALID_CREDENTIALS: [401, 'Неверный email или пароль'] as [number, string],
    INVALID_REFRESH_TOKEN: [401, 'Refresh-токен недействителен'] as [number, string],
    FORBIDDEN: [403, 'Недостаточно прав'] as [number, string],
    EMAIL_NOT_VERIFIED: [403, 'Email не подтверждён'] as [number, string],
    ACCOUNT_DISABLED: [403, 'Аккаунт деактивирован'] as [number, string],
    RESUME_NOT_FOUND: [404, 'Резюме не найдено'] as [number, string],
    COMPANY_NOT_FOUND: [404, 'Компания не найдена'] as [number, string],
    VACANCY_NOT_FOUND: [404, 'Вакансия не найдена'] as [number, string],
    EXPERIENCE_NOT_FOUND: [404, 'Запись об опыте не найдена'] as [number, string],
    EDUCATION_NOT_FOUND: [404, 'Запись об образовании не найдена'] as [number, string],
    APPLICATION_NOT_FOUND: [404, 'Отклик не найден'] as [number, string],
    FAVORITE_NOT_FOUND: [404, 'Вакансии нет в избранном'] as [number, string],
    EMAIL_ALREADY_EXISTS: [409, 'Пользователь с таким email уже зарегистрирован'] as [number, string],
    EMAIL_ALREADY_VERIFIED: [409, 'Email уже подтверждён'] as [number, string],
    SKILL_ALREADY_EXISTS: [409, 'Такой навык уже есть в справочнике'] as [number, string],
    APPLICATION_ALREADY_EXISTS: [409, 'Вы уже откликались на эту вакансию этим резюме'] as [number, string],
    FAVORITE_ALREADY_EXISTS: [409, 'Вакансия уже в избранном'] as [number, string],
    VACANCY_NOT_ACTIVE: [409, 'Вакансия закрыта для откликов'] as [number, string],
    RESUME_NOT_PUBLISHED: [409, 'Резюме не опубликовано'] as [number, string],
    INVALID_STATUS_TRANSITION: [409, 'Недопустимый переход статуса отклика'] as [number, string],
    COMPANY_HAS_VACANCIES: [409, 'Нельзя удалить компанию с вакансиями'] as [number, string],
    VACANCY_HAS_APPLICATIONS: [409, 'Нельзя удалить вакансию с откликами'] as [number, string],
    RESUME_HAS_APPLICATIONS: [409, 'Нельзя удалить резюме с откликами'] as [number, string],
    APPLICATION_NOT_WITHDRAWABLE: [409, 'Отклик нельзя отозвать'] as [number, string],
    VALIDATION_ERROR: [422, 'Ошибка валидации данных'] as [number, string],
    TOO_MANY_REQUESTS: [429, 'Слишком много запросов'] as [number, string],
    INTERNAL_ERROR: [500, 'Внутренняя ошибка сервера'] as [number, string],
    NOT_FOUND: [404, 'Адрес не найден'] as [number, string],
    SERVICE_UNAUTHORIZED: [401, 'Сервисный токен недействителен'] as [number, string],
    INVALID_CLIENT: [401, 'Неверные учётные данные сервиса'] as [number, string],
    SERVICE_FORBIDDEN: [403, 'Операция недоступна вызывающему сервису'] as [number, string],
    AUDIENCE_NOT_ALLOWED: [403, 'Клиенту не разрешено обращаться к этому сервису'] as [number, string],
    JOB_NOT_FOUND: [404, 'Задача не найдена'] as [number, string],
    INDEX_REBUILD_IN_PROGRESS: [409, 'Перестроение индекса уже выполняется'] as [number, string],
    SERVICE_UNAVAILABLE: [503, 'Сервис временно недоступен'] as [number, string],
    UPSTREAM_TIMEOUT: [504, 'Превышено время ожидания зависимого сервиса'] as [number, string],
};
